### PR TITLE
feat(GridEngine): steppedOn observable

### PR DESCRIPTION
**Pull request by zewa666**
related issue https://github.com/Annoraaq/grid-engine/issues/244

### CODE REVIEW

**Comment by zewa666** [comment]
Hey there @Annoraaq, thought I'd give this one a try.

Anything else you'd want me to add to this one? Like docs updates or the likes?

**Review by Annoraaq — CHANGES_REQUESTED** [review]
Looks good so far!

Can you please run prettier on the changes? I know there are no contribution guidelines yet, so you couldn't know. I will add some in the future.

You can either use a prettier plugin for your editor/IDE or you can run prettier from the command line.

For example `npx prettier -w src/**/*.ts`.

I see that I will add a prettier check to the CI/CD pipeline.

**Comment by zewa666** [comment]
makes sense, will do today in the evening.

**Comment by zewa666** [comment]
@Annoraaq, I've updated your eslint config to include the `require-await` rule to highlight the mentioned superfluous `async` keyword. While doing so I found a couple of other places this happened, including exactly the one I've copied as stub for my test :)

Now while doing that I've noticed you do lint js files, namely the eslint and jest configurations as well. I'm not really sure whether this makes a whole lot of sense but nevertheless the missing paserOptions are now set as well and the only side-effect required was having to add the two files explicitly in the tsconfig.json include section.

Prettier was applied as well .. shrug looking at the outcome now I know why I skipped it the whole time :rofl: 

Ideally, to avoid these kind of issues in future, I'd recommend adding [Husky](https://www.npmjs.com/package/husky) with a [pre-commit hook](https://prettier.io/docs/en/precommit.html). But that went way to far for the scope of this PR plus is definitely something up to you to decide

**Review by Annoraaq — APPROVED** [review]
I don't think there was a special reason for linting the js files. So I would say it doesn't really matter. However, the require-await rule makes sense 👍 

A pre-commit hook is a good idea.

**Pull request merged**
